apiVersion: v1
kind: ConfigMap
metadata:
  name: hellogo-config
  namespace: {{ .Values.namespace }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  DB_TYPE: {{ .Values.config.dbType | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_USER: {{ .Values.config.dbUser | quote }}
  JWT_EXPIRES: {{ .Values.config.jwtExpires | quote }}
  JWT_REFRESH_EXPIRES: {{ .Values.config.jwtRefreshExpires | quote }}
  LOGIN_MAX_FAILS: {{ .Values.config.loginMaxFails | quote }}
  LOGIN_LOCK_TTL: {{ .Values.config.loginLockTTL | quote }}
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
