apiVersion: v1
kind: Secret
metadata:
  name: hellogo-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.mysql.rootPassword | quote }}
  jwt-secret: {{ .Values.config.jwtSecret | quote }}
