apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: auth-service
  ports:
    - name: grpc
      port: {{ .Values.services.auth.grpcPort }}
      targetPort: grpc
