apiVersion: v1
kind: Service
metadata:
  name: permission-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: permission-service
  ports:
    - name: grpc
      port: {{ .Values.services.permission.grpcPort }}
      targetPort: grpc
    - name: health
      port: {{ .Values.services.permission.healthPort }}
      targetPort: health
